# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Debug-Dev' => :debug,
  'Debug-Prod' => :debug,
  'Debug-Tst' => :debug,
  'Debug-IllinoisDev' => :debug,
  'Debug-IllinoisProd' => :debug,
  'Debug-IllinoisTst' => :debug,

  'Profile' => :release,
  'Profile-Dev' => :release,
  'Profile-Prod' => :release,
  'Profile-Tst' => :release,
  'Profile-IllinoisDev' => :release,
  'Profile-IllinoisProd' => :release,
  'Profile-IllinoisTst' => :release,

  'Release' => :release,
  'Release-Dev' => :release,
  'Release-Prod' => :release,
  'Release-Tst' => :release,
  'Release-IllinoisDev' => :release,
  'Release-IllinoisProd' => :release,
  'Release-IllinoisTst' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

def applibs
    pod 'GoogleMaps', '7.2.0'
    pod 'ZXingObjC', '3.6.4'

#   pod 'SeosMobileKeysSDK', :path => '../../libs/hid-origo/ios/Debug/SeosMobileKeysSDK.podspec'
#   pod 'OrigoSDK', :path => '../../libs/hid-origo/ios/Debug/OrigoSDK.podspec'

    pod 'SeosMobileKeysSDK-Debug', :configuration => ['Debug', 'Debug-Dev', 'Debug-IllinoisDev', 'Debug-Prod', 'Debug-IllinoisProd', 'Debug-Tst', 'Debug-IllinoisTst'], :path => '../libs/hid-origo/ios/Debug/SeosMobileKeysSDK-Debug.podspec'
    pod 'SeosMobileKeysSDK-Release', :configuration => ['Release', 'Release-Dev', 'Release-IllinoisDev', 'Release-Prod', 'Release-IllinoisProd', 'Release-Tst', 'Release-IllinoisTst'], :path => '../libs/hid-origo/ios/Release/SeosMobileKeysSDK-Release.podspec'
    pod 'OrigoSDK-Debug', :configuration => ['Debug', 'Debug-Dev', 'Debug-IllinoisDev', 'Debug-Prod', 'Debug-IllinoisProd', 'Debug-Tst', 'Debug-IllinoisTst'], :path => '../libs/hid-origo/ios/Debug/OrigoSDK-Debug.podspec'
    pod 'OrigoSDK-Release', :configuration => ['Release', 'Release-Dev', 'Release-IllinoisDev', 'Release-Prod', 'Release-IllinoisProd', 'Release-Tst', 'Release-IllinoisTst'], :path => '../libs/hid-origo/ios/Release/OrigoSDK-Release.podspec'
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  applibs
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

target 'Illinois' do
  use_frameworks!
  use_modular_headers!
  applibs
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
